language: node_js
node_js:
  - "stable"

before_install: 
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose 
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose build

script:
  - docker-compose run front npm test -- --coverage 
  - docker-compose run front npm run build

after_success:
  - docker-compose run front npm run coveralls

deploy:
  - provider: heroku
    skip_cleanup: true
    api_key:
      secure: ${HEROKU_KEY}
    app: gbi-frontend2-staging
    on:
      repo: fga-eps-mds/2018.2-GamesBI-FrontEnd
      branch: develop
  - provider: heroku
    skip_cleanup: true
    api_key:
      secure: ${HEROKU_KEY}
    app: gbi-frontend2-production
    on:
      repo: fga-eps-mds/2018.2-GamesBI-FrontEnd
      branch: master
