language: node_js
node_js:
  - "stable"
before_install: docker-compose build
script:
  - docker-compose run web npm test -- --coverage 
  - docker-compose run web npm run build

after_success:
  - docker-compose run web npm run coveralls

deploy:
  provider: surge
  skip_cleanup: true
  domain: gamesBI.surge.sh
  project: ./build/
on:
  branch: master
