language: node_js
node_js:
  - "stable"
before_install: docker-compose build
script:
  - docker-compose run front npm test -- --coverage 
  - docker-compose run front npm run build

after_success:
  - docker-compose run front npm run coveralls

deploy:
  - provider: heroku
    skip_cleanup: true
    api_key:
      secure: ${HEROKU_KEY}
    app: gbi-frontend-staging
    on:
      repo: fga-eps-mds/2018.2-GamesBI-FrontEnd
      branch: develop
  - provider: heroku
    skip_cleanup: true
    api_key:
      secure: ${HEROKU_KEY}
    app: gbi-frontend-production
    on:
      repo: fga-eps-mds/2018.2-GamesBI-FrontEnd
      branch: master
