version: '3.5'

services:
  front:
    build: .
    command: npm start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - COVERALLS_REPO_TOKEN
      - REACT_APP_CROSSDATA_URL=http://localhost:8004
    networks:
      - proxynet
  cucumber:
    build: 
      context: cucumber
      dockerfile: Dockerfile
    command : cucumber --order random
    working_dir: /app
    volumes:
      - ./cucumber/tmp:/app/tmp
      - ./cucumber/features:/app/features
    environment:
      ROOT_URL: http://front:3000
    networks:
      - proxynet

networks:
  proxynet:
    name: GamesBI-network
