version: '3'

services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - COVERALLS_REPO_TOKEN
    env_file:
      - .env
