version: '3'

services:
  front:
    build: .
    command: npm start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - COVERALLS_REPO_TOKEN
      - REACT_APP_CROSSDATA_URL=https://gbi-crossdata-staging.herokuapp.com
