version: '3.5'

services:
  web:
    build: .
    command : cucumber --order random
    working_dir: /app
    volumes:
      - ./tmp:/app/tmp
      - ./features:/app/features
    environment:
      ROOT_URL: http://front:3000
    privileged: true
    networks:
      - proxynet

networks:
  proxynet:
    name: GamesBI-network
